Breakers_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Register_Login.urls"),name='Register_Login'),
    path('', include("categories_and_products.urls"),name='categories_and_products'),
    path('', include("cart_and_orders.urls"),name='cart_and_orders'),
    path('', include('django.contrib.auth.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart_and_orders/urls.py
from django.urls import path
from . import views

app_name = 'cart_and_orders'


urlpatterns = [
    path('cart', views.cart, name='cart'),
    path('yourorders', views.yourorders, name='yourorders'),

    path('order_sent', views.order_sent, name='order_sent'),
    path('email_template', views.email_template, name='email_template'),
    path('order_confirm', view = views.order_confirm, name='order_confirm'),

    # Payments
    path('PaymentChoice', views.PaymentChoice, name='PaymentChoice'),
    path('CardsPayment', views.CardsPayment, name='CardsPayment'),
    path('WalletPayment', views.WalletPayment, name='WalletPayment'),
    path('fawrypay', views.fawrypay, name='fawrypay'),

    path('PaymentFailed', views.PaymentFailed, name='PaymentFailed'),
    
    path('<int:id>', views.deleting, name='deleting'),
    
]

categories_and_products/urls.py
from django.urls import path
from . import views


app_name = 'categories_and_products'


urlpatterns = [
    path('',views.index,name='index',),
    path('games',views.games,name='games'),
    path('store',views.store,name='store'),
    path('details/<slug:categoryslug>/',views.code_details,name='code_details'),
    path('searchedPage',views.searchedPage,name='searchedPage'),
    path('<slug:Gameslug>/',views.GamesCodes,name='GamesCodes'),
    path('filter',views.filtering_test,name='filter'),
    path('privacy_policy',views.privacy_policy,name='privacy_policy'),
    path('refund',views.refund,name='refund')
]

cart_and_orders/models.py
from urllib import request
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.dispatch import receiver
from categories_and_products.models import Code_Categories
from django.utils import timezone
from datetime import timedelta
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext as _


# Create your models here.

status = (
    ('Pending', 'Pending'),
    ('Success', 'Success'),
)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, unique=True)
    total_price = models.FloatField(default=0)
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

    def calculatingTotal(request, self):
        cartItem = CartItems.objects.filter(
            user=request.user, ordered=False, paid=False)
        print(cartItem.price)
        return


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    comment = models.TextField(max_length=2000, blank=True, null=True)
    totalPrice = models.FloatField(default=0)
    total_price_after_taxes = models.FloatField(
        default=0, verbose_name='After Taxes')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    order_response = models.CharField(max_length=1000, blank=True,)
    paid_by = models.CharField(max_length=1000, blank=True,)

    def __str__(self):
        return str(self.id)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


@receiver(pre_save, sender=Order)
def calculatedFromSales(sender, **kwargs):
    orders = kwargs['instance']
    total_price_after_taxes = orders.totalPrice + \
        2 + (0.021 * orders.totalPrice)
    orders.total_price_after_taxes = total_price_after_taxes


class Codes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    code = models.CharField(max_length=1000, blank=True, unique=True)
    codeCategory = models.ForeignKey(
        Code_Categories, on_delete=models.CASCADE,)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    paid = models.BooleanField(default=False)
    ordered = models.BooleanField(default=False)
    addToCart = models.BooleanField(default=False)
    profit = models.FloatField(default=0, verbose_name='Profit From This Code')
    total_profit_calculated_from_sales = models.FloatField(
        default=0, verbose_name='Profit From Orders')
    price = models.FloatField(default=0, verbose_name='Price Of This Code')
    status = models.CharField(
        max_length=50, choices=status, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Codes"

    def __str__(self):
        return self.code


@receiver(pre_save, sender=Codes)
def calculatedFromSales(sender, **kwargs):
    codes = kwargs['instance']
    codes.price = float(codes.codeCategory.price)
    codes.profit = float(codes.codeCategory.price) - \
        float(codes.codeCategory.price_bought_by)


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    orderId = models.ForeignKey(
        Order, on_delete=models.CASCADE, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    codeCategory = models.ForeignKey(Code_Categories, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    quantity = models.IntegerField(default=1, name='quantity')
    created = models.DateTimeField(auto_now_add=True)
    totalOrderItemPrice = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=50, choices=status, blank=True, null=True)

    class Meta:
        verbose_name_plural = "CartItems"

    def deleteing_item(self):
        return reverse('cart_and_orders:deleting', args=[self.id])

    def __str__(self):
        return str(self.user.email) + " " + str(self.codeCategory.codeCategory)


        
    # def save(self, *args, **kwargs):
        # if settings.SESSION_EXPIRE_SECONDS > 10:
        #   print("Hello")
        # else:
        #     print("NOT")

@receiver(pre_save, sender=CartItems)
def correct_price(sender, **kwargs):
    cart_items = kwargs['instance']
    price_of_codeCategory = Code_Categories.objects.get(
        id=cart_items.codeCategory.id)
    cart_items.totalOrderItemPrice = cart_items.quantity * \
        float(price_of_codeCategory.price)
    total_cart_items = CartItems.objects.filter(user=cart_items.user)




def get_label(sender, self, **kwargs):
    cart_items = kwargs['instance']
    now = timezone.now()
    periodic_time = cart_items.created + timedelta(days=0, hours=0, seconds=10)
    if now > periodic_time:
        CartItems.objects.filter(id=self.id).delete()
        print("An hour has been Passed")
    else:
        print("hour is not Passed yet")

cart_and_orders/forms.py
from django import forms

class BromoCodeForm(forms.Form):
    code = forms.CharField(max_length=20,required=False, empty_value=None)

    def clean(self):
        cleaned_data = super(BromoCodeForm, self).clean()
        return cleaned_data

cart_and_orders/views.py
from datetime import datetime, timedelta
from django.utils import timezone
from django.shortcuts import redirect, render
from django.utils.translation import gettext as _
from django.template.loader import render_to_string
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from cart_and_orders.emptying_cart import deleting_from_cart, reset_all_users_cartItems_and_release_codes
from cart_and_orders.models import Cart, CartItems, Codes, Order
from django.db.models import Sum
import requests
import hashlib

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

# Rest API
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from categories_and_products.models import Code_Categories
# Create your views here.


def send_code_email(request, order_codes):
    subject, from_email, to = 'Sending Code Orders', 'noreply1@quranfordeaf.com',  request.user.email
    text_content = 'This is an important message.'
    print(order_codes)
    context = {
        'order_codes': order_codes,
        'user': request.user
    }
    html_content = render_to_string('order_sent.html', context)
    print("CODESS", order_codes)

    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
    messages.success(request, _('Check YOUR ORDERS section or you Email'))


def yourorders(request):
    reset_all_users_cartItems_and_release_codes(request)
    if request.user.is_authenticated:
        user_codes = Codes.objects.filter(
            user=request.user, addToCart=True, ordered=True).order_by('-created')
        order = Order.objects.filter(
            user=request.user, paid=True).order_by('-ordered_date')

        context = {
            'codes': user_codes,
            'order': order,
        }
    else:
        messages.error(request, _('* Login First Please'))
        return redirect('Register_Login:login')

    return render(request, 'yourorders.html', context)


def order_confirm(request,):
    cart = Cart.objects.get(user=request.user)
    response = request.session.get('refrence')
    if CartItems.objects.filter(user=request.user, ordered=False, paid=False,status=None).exists():
        return redirect('cart_and_orders:cart')
    else:
        pass

    # Creating Order ID
    order_sent = Order.objects.create(
        user=request.user,
        totalPrice=cart.total_price,
        cart=cart,
        paid=True,
        order_response=response,
        paid_by='Opay'

    )
    print(response)
# Updating Code Data
    Codes.objects.filter(user=request.user, addToCart=True, ordered=False, active=True).update(
        order_id=order_sent.id, ordered=True, active=False,  status='Success',)

# Updating the cartItem with the order id that's ordered
    CartItems.objects.filter(user=request.user, ordered=True, paid=False,).update(
        orderId=order_sent.id,
        paid=True,
        status='Success'
    )

    # Updating the profit sum
    total_Profit_from_sales = Codes.objects.filter(
        ordered=True).aggregate(Sum('profit')).get('profit__sum')

    Codes.objects.filter(ordered=True, active=False,).update(
        total_profit_calculated_from_sales=total_Profit_from_sales,)

    print(total_Profit_from_sales)

    # Updating the total price in the cart
    Cart.objects.filter(user=request.user).update(total_price=0)

    order_codes = Codes.objects.filter(
        user=request.user, order_id=order_sent.id, ordered=True,)

    # Sending Email
    if order_sent:
        send_code_email(request, order_codes)
        Codes.objects.filter(
            user=request.user, order_id=order_sent.id, ordered=True,).update(paid=True)
        print('Email Sent')

    return render(request, "order_confirmation.html")


def email_template(request):
    return render(request, 'email_template.html')


def order_sent(request):
    reset_all_users_cartItems_and_release_codes(request)
    if request.user.is_authenticated:
        order_codes = Codes.objects.filter(
            user=request.user, addToCart=True, ordered=False)
        print(order_codes)
    else:
        messages.error(request, _('* Login First Please'))
        return redirect('Register_Login:login')
    return render(request, 'order_sent.html', {'order_codes': order_codes})


def cart(request):
    if request.user.is_authenticated:
        now = timezone.now()
        cartItemschecking = CartItems.objects.filter(
            user=request.user, ordered=False,).last()

        cartItems = CartItems.objects.filter(user=request.user, paid=False)
        cart = Cart.objects.filter(user=request.user)

        gettingcart = Cart.objects.get(user=request.user,)

        total_price_after_taxes = gettingcart.total_price + \
            2 + (0.02 * gettingcart.total_price)

        if cartItemschecking != None:

            periodic_time = cartItemschecking.created + \
                timedelta(days=0, hours=0, minutes=0, seconds=30)

            pendingTime = cartItemschecking.created + \
                timedelta(days=0, hours=3, minutes=0, seconds=0)

            if cartItemschecking.status == "Pending":
                if now > pendingTime:
                    messages.error(request, _(
                        '* Your Pending limit has been expiered'), extra_tags='danger')
                    deleting_from_cart(request)

            elif cartItemschecking.status == "Success":
                pass

            else:
                if now > periodic_time:
                    messages.error(request, _(
                        '* Your Cart has been expired'), extra_tags='danger')
                    deleting_from_cart(request)

        else:
            pass
            print("Your Cart is Empty")

        if request.method == 'POST':
            if cartItems.exists():
                print("exist")
                pass
            else:
                messages.error(request, _('* Your Cart is Empty, Please add to cart first'),
                               extra_tags='danger')

        context = {
            'cartItems': cartItems,
            'cart': cart,
            'total_price_after_taxes': total_price_after_taxes
        }

    else:
        reset_all_users_cartItems_and_release_codes(request)
        messages.error(request, _('* Login First Please'),
                       extra_tags='danger')
        return redirect('Register_Login:login')

    return render(request, 'cart.html', context)


def PaymentChoice(request):
    reset_all_users_cartItems_and_release_codes(request)
    cartItems = CartItems.objects.filter(user=request.user, ordered=False)
    if cartItems.exists():
        pass
    else:
        messages.error(request, _('* Your Cart is Empty, Please add to cart first'),
                       extra_tags='danger')
        return redirect('cart_and_orders:cart')

    return render(request, 'PaymentChoice.html')


def CardsPayment(request):
    if request.user.is_authenticated:

        Codes.objects.filter(user=request.user, addToCart=True,
                             ordered=False, active=True).update(status='Pending',)

        # Updating the cartItem with the order id that's ordered
        CartItems.objects.filter(user=request.user, ordered=False).update(
            status='Pending',
        )

        # Getting Refrence ID to link between payment & dashboard & store it in the session
        refrence = str(datetime.now()) + str(request.user.username)
        request.session['refrence'] = refrence

# Calculating the Taxes and adding it
        gettingcart = Cart.objects.get(user=request.user,)
        total_price_after_taxes = gettingcart.total_price + \
            2 + (0.021 * gettingcart.total_price)


# Sending Payment via API

        sending_payment_request = requests.post('https://api.opaycheckout.com/api/v1/international/cashier/create', headers={
            'MerchantId': '281822021682889',
            'Authorization': 'Bearer OPAYPUB16450080851810.3897884686987133',

        },
            json={
            "country": "EG",
            "reference": refrence,
            "amount": {
                "total": (total_price_after_taxes * 100),
                "currency": "EGP"
            },
            # Payment success page after payment
            "returnUrl": "https://breakers-store.com/order_confirm",
            "cancelUrl": "https://breakers-store.com/PaymentFailed",  # Payment Failed
            "callbackUrl": "https://your-call-back-url",
            "expireAt": 300,
            "userInfo": {
                "userEmail": str(request.user),
                "userId": str(request.user.id),
                "userMobile": str(request.user.PhoneNumber),
                "userName": str(request.user.username),
            },
            "productList": [
                {
                    "productId": "productId",
                    "name": "name",
                    "description": "description",
                    "price": 100,
                    "quantity": 2,
                }
            ],
            "payMethod": "BankCard"
        })

        print("URL", sending_payment_request.json())

# Checking the success code to continue the operation
        if sending_payment_request.json().get('code') != '00000':
            return redirect('cart_and_orders:PaymentFailed')
        else:
            amount = sending_payment_request.json().get('data').get('amount').get('total')
            request.session['amount'] = amount
            payment_url = sending_payment_request.json().get('data').get('cashierUrl')
            CartItems.objects.filter(user=request.user, ordered=False).update(
                ordered=True,
            )
            return redirect(str(payment_url),)
    else:
        messages.error(request, _('* Login First Please'), extra_tags='danger')
    return render(request, 'CardsPayment.html')

cart_and_orders/templates/PaymentChoice.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



            <main class="page-main">
                <div class="uk-grid" data-uk-grid>
                    <div class="uk-width-3-3@l">
                        <div class="widjet --filters">
                            <br><br><br>
                            <div class="widjet__head">
                                
                                <h3 class="uk-text-lead">Payment Methods </h3>
                            </div>
                
                        </div>
                        <div class="group-row">

                            <ul id="youzify-groups-list" class="item-list">

                                <li class="group-has-avatar youzify-show-cover">

                                   
                                    <div>
                                        <div> <a href="{% url 'cart_and_orders:CardsPayment' %}"> <img src="{% static "img/payment methods/visa.png" %}" width="400px" height="320px" /> </a></div>
                                       <br>
                                        <div class="item">
                                            <center><div class="item-title"><a href="{% url 'cart_and_orders:CardsPayment' %}" class="bp-group-home-link season-of-the-witch-home-link">Bank Cards</a></div></center>
                                            <div class="item-meta">
                                                <div class="group-status"> <i class="fas-fa-globe-asia"></i></div>
                                            </div>
                                            <center> <div class="game-card__price"><span>Taxes Fees : 2.1 % + 2 EGP </span></div></center>

                                        </div>
                                    
                                        <div class="action">
                                            <div class="group-button public generic-button"> <a href="{% url 'cart_and_orders:CardsPayment' %}" class="group-button leave-group"><i class="ico_arrow-circle-right-white"></i> Proceed to Payment </a> </div>
                                            
                                        </div>

                                    </div>
                                    
                                </li>


                                <li class="group-has-avatar youzify-show-cover">

                                   
                                    <div>
                                        <div> <a href="{% url 'cart_and_orders:CardsPayment' %}"> <img src="{% static "img/payment methods/meeza.png" %}" width="400px" height="320px" /> </a></div>
                                       <br>
                                        <div class="item">
                                            <center><div class="item-title"><a href="{% url 'cart_and_orders:CardsPayment' %}" class="bp-group-home-link season-of-the-witch-home-link">Meeza Cards</a></div></center>
                                            <div class="item-meta">
                                                <div class="group-status"> <i class="fas-fa-globe-asia"></i></div>
                                            </div>
                                            <center> <div class="game-card__price"><span>Taxes Fees : 2.1 % + 2 EGP </span></div></center>

                                        </div>
                                    
                                        <div class="action">
                                            <div class="group-button public generic-button"> <a href="{% url 'cart_and_orders:CardsPayment' %}" class="group-button leave-group"><i class="ico_arrow-circle-right-white"></i> Proceed to Payment </a> </div>
                                            
                                        </div>

                                    </div>
                                    
                                </li>

                                <li class="group-has-avatar youzify-show-cover">

                                   
                                    <div>
                                        <div> <a href="{% url 'cart_and_orders:WalletPayment' %}">  <img src="{% static "img/payment methods/vcash.png" %}" width="400px" height="320px" /></a></div>
                                       <br>
                                        <div class="item">
                                            <center><div class="item-title"><a href="{% url 'cart_and_orders:WalletPayment' %}" class="bp-group-home-link season-of-the-witch-home-link">Mobile Wallets</a></div></center>
                                            <div class="item-meta">
                                                <div class="group-status"> <i class="fas-fa-globe-asia"></i></div>
                                            </div>
                                            <center> <div class="game-card__price"><span>Taxes Fees : 2.1 % + 2 EGP</span></div></center>

                                        </div>
                                    
                                        <div class="action">
                                            <div class="group-button public generic-button"> <a href="{% url 'cart_and_orders:WalletPayment' %}" class="group-button leave-group"><i class="ico_arrow-circle-right-white"></i> Proceed to Payment </a> </div>
                                            
                                        </div>

                                    </div>
                                    
                                </li>
                                <li class="group-has-avatar youzify-show-cover">


                                    
                                </li>
                               
                                <li class="group-has-avatar youzify-show-cover">

                                   
                                    <div>
                                        <div> <a href="{% url 'cart_and_orders:fawrypay' %}"> <img src="{% static "img/payment methods/fawry land.png" %}" width="400px" height="320px" /> </a></div>
                                       <br>
                                        <div class="item">
                                            <center><div class="item-title"><a href="{% url 'cart_and_orders:fawrypay' %}" class="bp-group-home-link season-of-the-witch-home-link">FawryPay</a></div></center>
                                            <div class="item-meta">
                                                <div class="group-status"> <i class="fas-fa-globe-asia"></i></div>
                                            </div>
                                            <center> <div class="game-card__price"><span>Soon</span></div></center>

                                        </div>
                                    
                                        <div class="action">
                                            <div class="group-button public generic-button"> <a href="{% url 'cart_and_orders:fawrypay' %}" class="group-button leave-group"><i class="ico_arrow-circle-right-white"></i> Proceed to Payment </a> </div>
                                            
                                        </div>

                                    </div>
                                    
                                </li> 
                            
                                

                            </ul>
              
                        </div>
                        
                        
                    </div>


                </div>
            </main>
        </div>
    </div>
{% endblock content %}

cart_and_orders/templates/PaymentFailed.html
Payment Failed

cart_and_orders/templates/callbackurl.html
{{callbackurldata}}

cart_and_orders/templates/cart.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
            <main class="page-main">
                <div class="uk-grid" data-uk-grid>
                    <div class="uk-width-2-3@l">
                       <br><br>
                        <div class="game-card --horizontal favourites-game">
                            {% for cartItems in cartItems %} 
                            <div class="game-card__box">
                                <div class="widjet-game__media"><a href="{{cartItems.codeCategory.get_absolute_url}}" ><img src="{{cartItems.codeCategory.image.url}}" alt="image"></a></div>
                                <div class="game-card__info"><a class="game-card__title" href="{{cartItems.codeCategory.get_absolute_url}}"> {{cartItems.codeCategory.codeCategory}}</a>
                                    <div class="game-card__genre">{{cartItems.codeCategory.game.gameName}} </div>
                                    <div class="game-card__rating-and-price">
                                        <div class="game-card__rating"><span> x{{cartItems.quantity}}</span><i></i></div>
                                        <div class="game-card__price"><span>L.E {{cartItems.codeCategory.price}} </span></div>
                                    </div>
                                    <div class="game-card__bottom">
                                        <div class="game-card__platform"><i class="ico_windows"></i><i class="ico_apple"></i></div>
                                    </div>
                                </div>
                                <div class = 'trash' ><a href="{{cartItems.deleteing_item}}"> <img src="{% static "img/trash.png" %}" width="40"> </a></div>
                            </div>
                            <hr>
                            {% endfor %}
                            <br>
                            
                            <div>
                                {% for cart in cart %}
                               <center> <h3 class="uk-text-lead">SubTotal : {{cart.total_price}}</h3></center>
                               {% endfor %}
                            </div>
                           
                        </div>
       
                        {% comment %} {% endif %} {% endcomment %}
                    </div> 
                    
                  <br><br><br><br>
                    
                   <div class="checkout-form">
                        <div class="form-login__box">
                            
                             {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li> {{ message }}</li>
                                {% endfor %}
                            </ul>
                            <br>
                            {% endif %}
                            {% for cart in cart %}
                            <div class="uk-heading-line uk-text-center"><span>Checkout</span></div>
                            <center> <h5 class = "notes"> * Fees are added depending on the payment method.</h5></center>

                            <br>
                       
                            {% endfor %}
                            
                            

                            <form method="POST">
								{% csrf_token %}
                                <div class="uk-margin">
                                    
                                    <hr>
                                    {% for cart in cart %}
                                    {% if cart.total_price == 0 %}
                                    <a  href = " {% url 'cart_and_orders:PaymentChoice' %}"><input href = "{% url 'categories_and_products:index' %}"  class="uk-button uk-button-danger uk-width-1-1"  value="Pay Now"></div></a>

                                    {% else %}
                                    <a  href = " {% url 'cart_and_orders:PaymentChoice' %}"><input href = "{% url 'categories_and_products:index' %}"  class="uk-button uk-button-danger uk-width-1-1"  value="Pay Now" ></div></a>
                                    {% endif %}
                                    {% endfor %}
                                    <hr>
                                    <a  href = "{% url 'categories_and_products:index' %}"><input href = "{% url 'categories_and_products:index' %}" class="uk-button secondary uk-width-1-1 "  value="Continue shopping"/></div></a>
                                  </form>
                                  <br>
                     
                                
                        </div>
                    </div> 
                    
                </div>
                
                
            </main>
        </div>
    </div>
    {% endblock content %}

cart_and_orders/templates/fawrypay.html
{{status_response}}