Breakers_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Register_Login.urls"),name='Register_Login'),
    path('', include("categories_and_products.urls"),name='categories_and_products'),
    path('', include("cart_and_orders.urls"),name='cart_and_orders'),
    path('', include('django.contrib.auth.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Register_Login/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from Register_Login.views import Register, activate_user, email_activated, logOut, signIn,email_sent,profile,password_reset_emailing


app_name = 'Register_Login'

urlpatterns = [
    path('register', view = Register, name='Register'),
    path('login', view = signIn, name='login'),
    path('logOut',view = logOut, name='logOut'),
    path('email_sent', view = email_sent, name='email_sent'),
    path(route='activate/<token>', view=activate_user, name='activate'),
    path('profile', view = profile, name='profile'),
    path('email_activated', view = email_activated, name='email_activated'),



    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),



    path('password_reset/done/', view = password_reset_emailing ,name='password_reset_emailing'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),


    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cart_and_orders/urls.py
from django.urls import path
from . import views

app_name = 'cart_and_orders'


urlpatterns = [
    path('cart', views.cart, name='cart'),
    path('yourorders', views.yourorders, name='yourorders'),

    path('order_sent', views.order_sent, name='order_sent'),
    path('email_template', views.email_template, name='email_template'),
    path('order_confirm', view = views.order_confirm, name='order_confirm'),

    # Payments
    path('PaymentChoice', views.PaymentChoice, name='PaymentChoice'),
    path('CardsPayment', views.CardsPayment, name='CardsPayment'),
    path('WalletPayment', views.WalletPayment, name='WalletPayment'),
    path('fawrypay', views.fawrypay, name='fawrypay'),

    path('PaymentFailed', views.PaymentFailed, name='PaymentFailed'),
    
    path('<int:id>', views.deleting, name='deleting'),
    
]

categories_and_products/urls.py
from django.urls import path
from . import views


app_name = 'categories_and_products'


urlpatterns = [
    path('',views.index,name='index',),
    path('games',views.games,name='games'),
    path('store',views.store,name='store'),
    path('details/<slug:categoryslug>/',views.code_details,name='code_details'),
    path('searchedPage',views.searchedPage,name='searchedPage'),
    path('<slug:Gameslug>/',views.GamesCodes,name='GamesCodes'),
    path('filter',views.filtering_test,name='filter'),
    path('privacy_policy',views.privacy_policy,name='privacy_policy'),
    path('refund',views.refund,name='refund')
]

Register_Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin,Group
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from django.utils.timezone import timedelta
from django.utils import timezone
from Breakers_Store import settings

from Register_Login.utils import AccessTokenGenerator





class UserManager(BaseUserManager):
    def get_by_natural_key(self, username):
        """
        To make email login case sensetive.
        """
        
        return self.get(email__iexact=username)

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        
        if not email:
            raise ValueError('Email does not included!')
        
        email = self.normalize_email(email)
        user = self.model(email=email, password=password, **extra_fields)
        user.set_password(password)
        user.save()
        
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        
        return self.create_user(email=email, password=password, **extra_fields)

class Profile(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(verbose_name='email address', unique=True)
    username = models.CharField(max_length=50, null=True)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    Age = models.CharField(max_length=10, null=True)
    city = models.CharField(max_length=60, null=True)
    PhoneNumber =  models.CharField(max_length=20, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    # ProfilePic = models.ImageField(upload_to="profile/", null=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email


class Newsletter(models.Model):
    email = models.EmailField(max_length=500, blank=True)
    def __str__(self):
        return self.email



class AccessToken(models.Model):
    token = models.CharField(max_length=500, blank=True)
    user = models.ForeignKey(to= Profile, on_delete=models.CASCADE, related_name='token')
    expires = models.DateTimeField()
    created = models.DateTimeField(auto_now=True, editable=False)
    
    def __str__(self):
        return self.token
    
    class Meta:
        ordering = ('-created',)

@receiver(pre_save, sender=AccessToken)
def token_save(sender, instance, **kwargs):
    instance.token = AccessTokenGenerator().make_token(instance.user)
    instance.expires = timezone.now() + timedelta(seconds=settings.AUTH_EMAIL_ACTIVATE_EXPIRE)
    

Register_Login/forms.py
from django import forms
from Register_Login.models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import authenticate



class RegisterForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = ('email','username', 'first_name', 'last_name', 'password1','Age', 'PhoneNumber','city')
        error_messages = {
            'email': {
                'unique': _("This entry has been registered before."),
            }
        }
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password1")
        confirm_password = cleaned_data.get("password2")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class LoginForm(forms.Form):
    email = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self,*args,**kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(email = email, password=password)
        if not user:
            raise forms.ValidationError("This user does not exist")
        if not user.check_password(password):
            raise forms.ValidationError("Password is incorrect")
        if not user.is_active:
            raise forms.ValidationError("This user is not active, check Your inbox or make sure you logged in with valid email")
        return super(LoginForm,self).clean(*args,**kwargs)


class CompleteProfile(forms.ModelForm):
    class Meta:
        pass

Register_Login/views.py
# Importing Django Libraries required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.http.response import HttpResponse
from django.contrib.auth import authenticate, logout
from django.contrib import messages
from django.contrib.auth import authenticate, login as user_login
from django.template.loader import render_to_string
from django.utils import timezone
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate
from django.utils.translation import gettext as _
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMessage

# Importing the utilts file
from Register_Login.utils import AccessTokenGenerator

# Importing setting from the main project
from Breakers_Store import settings


# Importing Models
from Register_Login.models import AccessToken, Profile
# from cart_and_orders.models import Cart

# Importing Forms
from Register_Login.forms import LoginForm, RegisterForm
from cart_and_orders.emptying_cart import reset_all_users_cartItems_and_release_codes
from cart_and_orders.models import Cart, Codes


# Email Confirm SignUp
def send_tracking(user):
    print(user)
    user = Profile.objects.filter(id=user.id).first()
    last_token = user.token.filter(
        user=user, expires__gt=timezone.now()).first()
    if not last_token:
        access_token = user.token.create(user=user)
        return (access_token.token, 0)
    return (False, (last_token.expires - timezone.now()).total_seconds())

# Checking the token availablity & creating the cart


def token_check(user):
    token, time_tosend = send_tracking(user=user)
    if token:
        Cart.objects.create(
                    user=user,
                )
        return (token, time_tosend)
    return (None, time_tosend)


def send_activate_mail(request, user):
    token, time_tosend = token_check(user)
    if token:
        print(token)
        domain = get_current_site(request)
        subject = _('Activate user account')
        body = render_to_string('activate.html', {
            'user': user,
            'domain': domain,
            'token': token,
        })
        email = EmailMessage(
            subject, body, settings.EMAIL_HOST_USER, [user.email])
        print(email)
        email.send()

        messages.success(request, _('Kindly check your inbox & junk for confirmation,'))
    else:
        messages.error(request, _('Please varify the account (an email have been sent) please wait %(time_tosend)8.0f') % {
                       'time_tosend': time_tosend}, extra_tags='danger')




# This function is to create a new user profile & be saved in the models
@csrf_exempt
def Register(request):
    reset_all_users_cartItems_and_release_codes(request)
    if request.user.is_authenticated:
        return redirect('categories_and_products:index')
    else:
        if request.method == 'POST':
            print("Method is Post")
            form = RegisterForm(request.POST)
            email = form.data.get('email')
            first_name, last_name, username = form.data.get(
                'first_name'), form.data.get('last_name'), form.data.get('username')
            password = form.data.get('password1')
            city = form.data.get('city')
            Age, PhoneNumber = form.data.get(
                'Age'), form.data.get('PhoneNumber'),

            print(form.errors)
            if Profile.objects.filter(email = email).exists():
                messages.error(request, "This Email Exists !")
            else:
                user = Profile.objects.create_user(
                    email=email,
                    first_name=first_name,
                    last_name=last_name,
                    password=password,
                    username=username,
                    city=city,
                    Age=Age,
                    PhoneNumber=PhoneNumber,
            )
                send_activate_mail(request, user)
                if not user:                    
                    messages.error(request, "Your email is not active")
                    print('user is created but not active')
                else:
                    print(user, "KNown")
                return redirect('Register_Login:email_sent')
        else:
            print("Error")
            form = RegisterForm()
        return render(request, "Register.html",  {
        })


# Confirming sending email to user
def email_sent(request):
    return render(request, "email_sent.html")

def password_reset_emailing(request):
    return render(request, "registration/password_reset_completing.html")
# Logout Page


def activate_user(request, token):
    token = AccessToken.objects.filter(token=token).first()
    
    if token:
        last_token = AccessToken.objects.filter(user=token.user, expires__gt=timezone.now()).first()
        
        if last_token == token:
            
            if AccessTokenGenerator().check_token(token.user, token.token):       
                token.user.is_active = True
                token.user.save()
                messages.success(request, "Your account has been activated")
                return redirect('Register_Login:email_activated')
            return HttpResponse('already activated')
        return HttpResponse('timeout')

    return  HttpResponse('None found token')
    

def logOut(request):
    reset_all_users_cartItems_and_release_codes(request)
    logout(request)
    messages.info(request, "Your session has been ended, please login again")
    return render(request, 'LogOut.html',)


def email_activated(request):
    return render(request, 'email_activated.html',)



# Login View
def signIn(request):
    reset_all_users_cartItems_and_release_codes(request)
    form = LoginForm(request.POST, request.FILES)
    if request.user.is_authenticated:
        return redirect('categories_and_products:index')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, email=email, password=password)
            if form.is_valid():
                if user.is_active:
                    print("Post")
                    user_login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    print('Hello')
                    messages.error(request, "Your account is not active, Please Register with valid Email")
            else:
                messages.error(request, "Please Login with your right Credentials and check your email for activation")
                
        return render(request, 'login.html', {'form': form})



def profile(request):
    reset_all_users_cartItems_and_release_codes(request)
    if request.user.is_authenticated:
        user_codes = Codes.objects.filter(user=request.user, addToCart=True, ordered=True).order_by('-created')[:5] 
        context = {'user_codes' : user_codes}
    else:
        messages.error(request, _('* Login First Please'))
        return redirect('Register_Login:login')
    return render(request, "profile.html",context)

Register_Login/templates/LogOut.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Breaker Store - Promote your games now !</title>
    <meta content="Templines" name="author">
    <meta content="TeamHost" name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <meta name="format-detection" content="telephone=no">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">

    <link  type="image/x-icon"  rel="shortcut icon"  href="{% static "img/breakers_logo.png" %}"/>
    <link  rel="stylesheet"  href="{% static "css/libs.min.css" %}"/>
    <link  rel="stylesheet"  href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" href="{% static "css/youzify.min.css" %}">


    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">


</head>

<body class="page-login dark-theme">



    <!-- Loader-->
    <div id="page-preloader">
        <div class="preloader-1">
            <div class="loader-text">Loading</div>
            <span class="line line-1"></span>
            <span class="line line-2"></span>
            <span class="line line-3"></span>
            <span class="line line-4"></span>
            <span class="line line-5"></span>
            <span class="line line-6"></span>
            <span class="line line-7"></span>
            <span class="line line-8"></span>
            <span class="line line-9"></span>
        </div>

    </div>
    <!-- Loader end-->


    {% comment %} <div class="page-wrapper"> {% endcomment %}
        <main class="page-first-screen">
            <div class="uk-grid uk-grid-small uk-child-width-1-2@s uk-flex-middle uk-width-1-1" data-uk-grid>
                <div class="logo-big">
                    <a href="{% url 'categories_and_products:index' %}"><img src="{% static "img/logo/01.png" %}" alt="logo" class="animation-navspinv"></a>
                    <span>Breaker's Store</span>
					<br><br>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li> {{ message }} </li>
                        {% endfor %}
                    </ul>
                    <br><br>
                    {% endif %}
                   
                </div>
            </div>
            <div><span><a href = "/"> <h1>Home</h1></a></span></div>
        </main>
    {% comment %} </div> {% endcomment %}

    <script src="static/js/libs.js"></script>
    <script src="static/js/main.js"></script>
</body>

</html>

Register_Login/templates/activate.html
{% autoescape off %}

Hi {{user.first_name}} {{user.last_name}}

Please use the below link to verfiy your account

http://{{domain}}{% url 'Register_Login:activate' token %}

{% endautoescape %}

Register_Login/templates/email_activated.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Breaker Store - Promote your games now !</title>
    <meta content="Templines" name="author">
    <meta content="TeamHost" name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <meta name="format-detection" content="telephone=no">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">

    <link  type="image/x-icon"  rel="shortcut icon"  href="{% static "img/breakers_logo.png" %}"/>
    <link  rel="stylesheet"  href="{% static "css/libs.min.css" %}"/>
    <link  rel="stylesheet"  href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" href="{% static "css/youzify.min.css" %}">


    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">


</head>

<body class="page-login dark-theme">



    <!-- Loader-->
    <div id="page-preloader">
        <div class="preloader-1">
            <div class="loader-text">Loading</div>
            <span class="line line-1"></span>
            <span class="line line-2"></span>
            <span class="line line-3"></span>
            <span class="line line-4"></span>
            <span class="line line-5"></span>
            <span class="line line-6"></span>
            <span class="line line-7"></span>
            <span class="line line-8"></span>
            <span class="line line-9"></span>
        </div>

    </div>
    <!-- Loader end-->


    {% comment %} <div class="page-wrapper"> {% endcomment %}
        <main class="page-first-screen">
            <div class="uk-grid uk-grid-small uk-child-width-1-2@s uk-flex-middle uk-width-1-1" data-uk-grid>
                <div class="logo-big">
                    <img src="{% static "img/logo/01.png" %}" alt="logo" class="animation-navspinv">
                    <span>Breaker's Store</span>
					<br><br>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li> {{ message }} </li>
                        {% endfor %}
                    </ul>
                    <br><br>
                    {% endif %}
                   
                </div>
            </div>
            <div><span><a href = "{% url 'Register_Login:login' %}"> <h3 class="uk-text-lead" >Login</h3></a></span></div>
        </main>
    {% comment %} </div> {% endcomment %}

    <script src="static/js/libs.js"></script>
    <script src="static/js/main.js"></script>
</body>

</html>

Register_Login/templates/login.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Breaker Store - Promote your games now !</title>
    <meta content="Templines" name="author">
    <meta content="TeamHost" name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <meta name="format-detection" content="telephone=no">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">

    <link  type="image/x-icon"  rel="shortcut icon"  href="{% static "img/breakers_logo.png" %}"/>
    <link  rel="stylesheet"  href="{% static "css/libs.min.css" %}"/>
    <link  rel="stylesheet"  href="{% static "css/main.css" %}"/>
    <link rel="stylesheet" href="{% static "css/youzify.min.css" %}">


    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">


</head>

<body class="page-login dark-theme">



    <!-- Loader-->
    <div id="page-preloader">
        <div class="preloader-1">
            <div class="loader-text">Loading</div>
            <span class="line line-1"></span>
            <span class="line line-2"></span>
            <span class="line line-3"></span>
            <span class="line line-4"></span>
            <span class="line line-5"></span>
            <span class="line line-6"></span>
            <span class="line line-7"></span>
            <span class="line line-8"></span>
            <span class="line line-9"></span>
        </div>

    </div>
    <!-- Loader end-->


    {% comment %} <div class="page-wrapper"> {% endcomment %}
        <main class="page-first-screen">
            <div class="uk-grid uk-grid-small uk-child-width-1-2@s uk-flex-middle uk-width-1-1" data-uk-grid>
                <div class="logo-big">
                    <a href="{% url 'categories_and_products:index' %}"><img src="{% static "img/logo/01.png" %}" alt="logo" class="animation-navspinv"></a>
                    <span>Breaker's Store</span>                   
                </div>
                <div>
             
                    <div class="form-login">
                        <div class="form-login__box">
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li> {{ message }} </li>
                                {% endfor %}
                            </ul>
                        
                            {% endif %}
                            <div class="uk-heading-line uk-text-center"><span>Login</span></div>
                            <form method="POST">
								{% csrf_token %}
                   
                                <div class="uk-margin"><input class="uk-input" name="email" id="email" type="email" placeholder="Email" ></div>
                                <div class="uk-margin"><input class="uk-input"  name="password" id="password" type="password" placeholder="Password"></div>
                                <div class="uk-margin">
                                    <input type="submit" name="signin" id="signin" class="uk-button uk-button-danger uk-width-1-1"  value="Log in"/></div>
                             
                                    <div class="uk-margin uk-text-center"><a href="{% url 'Register_Login:password_reset' %}">Forgotten password?</a></div>

                                    
                                   
                                    <hr>
                                    <div class="uk-text-center"><span>Don’t have an account?</span><a class="uk-margin-small-left" href="register">Register</a></div>
                                  </form>
                                  <br>
                                  <table border="0" cellpadding="10" cellspacing="0" class="social_block block-1" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                                    <tr>
                                    <td class="pad">
                                    <div class="alignment" style="text-align:center;">
                                    <table border="0" cellpadding="0" cellspacing="0" class="social-table" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;" width="188px">
                                    <tr>
                                    <td style="padding:0 25px 0 5px;"><a href="https://www.facebook.com/breakersstoreeg" target="_blank"><img alt="Facebook" height="32" src="{{site}}{% static 'img/facebook2x.png'%}" style="display: block; height: auto; border: 0;" title="Facebook" width="32"/></a></td>
                                    <td style="padding:0 25px 0 5px;"><a href="https://twitter.com/" target="_blank"><img alt="Twitter" height="32" src="{{site}}{% static 'img/twitter2x.png'%}" style="display: block; height: auto; border: 0;" title="Twitter" width="32"/></a></td>
                                    <td style="padding:0 25px 0 5px;"><a href="https://instagram.com/" target="_blank"><img alt="Instagram" height="32" src="{{site}}{% static 'img/instagram2x.png'%}" style="display: block; height: auto; border: 0;" title="Instagram" width="32"/></a></td>
                                    </tr>
                                    </table>
                                    </div>
                                    </td>
                                    </tr>
                                    </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    {% comment %} </div> {% endcomment %}

    <script src="static/js/libs.js"></script>
    <script src="static/js/main.js"></script>
</body>

</html>

Register_Login/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock title %}

{% block content %} 

<main class="page-main">
    <div class="uk-grid" data-uk-grid>
        <div class="uk-width-2-3@l">
            <br><br>
            <div class="widjet --profile">
                
                <div class="widjet__head">
                    
                </div>
                <div class="widjet__body">
                    <div class="user-info">
                        <div class="user-info__box">
                            <div class="user-info__title">{{user.first_name}} {{user.last_name}}</div>
                            {% comment %} {% for user_data in user_data %} {% endcomment %}
                            <div class="user-info__text">Username: {{user.username}}</div>
                            {% comment %} {% endfor %} {% endcomment %}
                        </div>
                    {% comment %} </div><a class="uk-button uk-button-danger" href="04_profile.html"><i class="ico_edit"></i><span class="uk-margin-small-left">Edit Profile</span></a> {% endcomment %}
                </div>
            </div>
            <br>

            <div class="widjet --bio">
                <div class="widjet__head">
                    <h3 class="uk-text-lead">Bio</h3>
                </div>
                <div class="widjet__body">
                    <span>Email: {{user.email}} </span>
                    <span>Age: {{user.Age}}</span>
                    <span>City: {{user.city}} </span>
                    
                    <span>PhoneNumber: {{user.PhoneNumber}}</span>                    
                
                
                </div>
                
            </div>
            <div class="widjet --activity">
                <div class="widjet__head">
                    <h3 class="uk-text-lead">Recent Orders</h3><a href="{% url 'cart_and_orders:yourorders' %}">View All</a>
                </div>
                {% for user_codes in user_codes %}
                <div class="widjet__body">
                    
                    <div class="widjet-game">
                        
                        <div class="widjet-game__media"><a><img src="{{user_codes.codeCategory.image.url}}" alt="image"></a></div>
                        <div class="widjet-game__info"><a class="widjet-game__title"> {{user_codes.code}}</a>
                            <div class="widjet-game__record">{{user_codes.codeCategory.codeCategory}}</div>
                            <div class="widjet-game__last-played">{{user_codes.created}}</div>
                        </div>
                    </div>
                    
                    
                </div>
                {% endfor %}

            </div>
        </div>
        
    </div>
</main>


{% endblock content %}