Breakers_Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Register_Login.urls"),name='Register_Login'),
    path('', include("categories_and_products.urls"),name='categories_and_products'),
    path('', include("cart_and_orders.urls"),name='cart_and_orders'),
    path('', include('django.contrib.auth.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Register_Login/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from Register_Login.views import Register, activate_user, email_activated, logOut, signIn,email_sent,profile,password_reset_emailing


app_name = 'Register_Login'

urlpatterns = [
    path('register', view = Register, name='Register'),
    path('login', view = signIn, name='login'),
    path('logOut',view = logOut, name='logOut'),
    path('email_sent', view = email_sent, name='email_sent'),
    path(route='activate/<token>', view=activate_user, name='activate'),
    path('profile', view = profile, name='profile'),
    path('email_activated', view = email_activated, name='email_activated'),



    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),



    path('password_reset/done/', view = password_reset_emailing ,name='password_reset_emailing'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),


    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cart_and_orders/urls.py
from django.urls import path
from . import views

app_name = 'cart_and_orders'


urlpatterns = [
    path('cart', views.cart, name='cart'),
    path('yourorders', views.yourorders, name='yourorders'),

    path('order_sent', views.order_sent, name='order_sent'),
    path('email_template', views.email_template, name='email_template'),
    path('order_confirm', view = views.order_confirm, name='order_confirm'),

    # Payments
    path('PaymentChoice', views.PaymentChoice, name='PaymentChoice'),
    path('CardsPayment', views.CardsPayment, name='CardsPayment'),
    path('WalletPayment', views.WalletPayment, name='WalletPayment'),
    path('fawrypay', views.fawrypay, name='fawrypay'),

    path('PaymentFailed', views.PaymentFailed, name='PaymentFailed'),
    
    path('<int:id>', views.deleting, name='deleting'),
    
]

categories_and_products/urls.py
from django.urls import path
from . import views


app_name = 'categories_and_products'


urlpatterns = [
    path('',views.index,name='index',),
    path('games',views.games,name='games'),
    path('store',views.store,name='store'),
    path('details/<slug:categoryslug>/',views.code_details,name='code_details'),
    path('searchedPage',views.searchedPage,name='searchedPage'),
    path('<slug:Gameslug>/',views.GamesCodes,name='GamesCodes'),
    path('filter',views.filtering_test,name='filter'),
    path('privacy_policy',views.privacy_policy,name='privacy_policy'),
    path('refund',views.refund,name='refund')
]

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">

    <title>{% block title %}    {% endblock title %}</title>
    
    <meta content="Templines" name="author">
    <meta content="Breaker's Store is a Gaming website for buying codes for promoting your games." name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="true">
    <meta name="format-detection" content="telephone=no">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">

    <meta name='og:image' content={% static "img/breakers_logo.png" %}>

    <link  type="image/x-icon" rel="shortcut icon"  href="{% static "img/breakers_logo.png" %}"/>
    <link  rel="stylesheet"  href="{% static "css/libs.min.css" %}"/>
    <link  rel="stylesheet"  href="{% static "css/main.css" %}"/>
    <link  rel="stylesheet"   href="{% static "css/youzify.min.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" />


</head>



<body class="page-home dark-theme">
  
      <!-- Loader-->
    <div id="page-preloader">
        <div class="preloader-1">
            <div class="loader-text">Loading</div>
            <span class="line line-1"></span>
            <span class="line line-2"></span>
            <span class="line line-3"></span>
            <span class="line line-4"></span>
            <span class="line line-5"></span>
            <span class="line line-6"></span>
            <span class="line line-7"></span>
            <span class="line line-8"></span>
            <span class="line line-9"></span>
        </div>

    </div>
    <!-- Loader end-->

    <div class="page-wrapper">
        <header class="page-header">
            <div class="page-header__inner">
                
                <div class="page-header__sidebar">
                    <div class="page-header__menu-btn"><button class="menu-btn ico_menu is-active"></button></div>
                    
                    <div class="page-header__logo"> <a href="{% url 'categories_and_products:index' %}"><img src="{% static "img/breakers_logo.png" %}" alt="logo"></a>
                        <span href="{% url 'categories_and_products:index' %}"  class="page-header__logo_text">Breaker's Store</span>
                    </div>
                    
                </div>

    
                <div class="page-header__content">
                    <div class="page-header__search">
                        <br>
                        <form method="GET" action="{% url 'categories_and_products:searchedPage' %}" class="w-100">
                        <div class="search">
                                {% csrf_token %}
                                
                            <div class="search__input"><input class="search" name="searched" placeholder="Search" ></div>
                            
                            <div class="search__btn">
                                <button type="submit"><i class="ico_search"></i></button>
                            </div>
                        </div>
                    </form>
                    </div>
                  
                </div>
             
                
               
            </div>
            
        </header>
        
        <div class="page-content">
            
            <aside class="sidebar is-show" id="sidebar">
                <div class="sidebar-box">
                    <ul class="uk-nav">
                        
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'Register_Login:profile' %}"> <i class="ico_profile"></i> <span>{{user.first_name}} {{user.last_name}}</span></a></li>
                        <hr>
                        {% endif %}

                        <li><a href="{% url 'categories_and_products:index' %}"><i class="ico_home"></i><span>Home</span></a></li>
                        <li class="uk-nav-header">Account</li>
                        <li><a href="{% url 'Register_Login:profile' %}"><i class="ico_profile"></i><span>Profile</span></a></li>
                        <li><a href="{% url 'cart_and_orders:yourorders' %}"><i class="ico_market"></i><span>Your Orders</span></a></li>
                        <li><a href="{% url 'cart_and_orders:cart' %}"><i class="ico_shopping-cart"></i><span>Cart</span></a></li>

            

                        <li class="uk-nav-header">Main</li>

                        <li><a href="{% url 'categories_and_products:games' %}"><i class="ico_emoji-happy"></i><span>Products</span></a></li>
                        <li><a href="{% url 'categories_and_products:store' %}"><i class="ico_store"></i><span>All Cards</span></a></li>
                        

                        {% comment %} <li class="uk-nav-header">Support</li>
                        <li><a href="#modal-report" data-uk-toggle> <i class="ico_call"></i><span>Contact Us</span></a></li>
                        <li><a href="#modal-help" data-uk-toggle>   <i class="ico_help"></i><span>Help</span></a></li> {% endcomment %}
                        <hr>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'Register_Login:logOut' %}"><i class="ico_arrow-circle-left"></i><span>Logout</span></a></li>
                        {% else %}
                        <li><a href="{% url 'Register_Login:login' %}"><i class="ico_arrow-circle-right" ></i><span>Login</span></a></li>
                        {% endif %}
                        <li><a href = "https://www.facebook.com/breakersstoreeg" ><span>- Have a problem ? Contact Us</span></a></li>
                        <li><a href = "{% url 'categories_and_products:privacy_policy'%}" ><span>- Privacy Policy</span></a></li>
                        <li><a href = "{% url 'categories_and_products:refund'%}" ><span>- Refund Policy</span></a></li>
                    </ul>
                    <table border="0" cellpadding="10" cellspacing="0" class="social_block block-1" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;" width="100%">
                        <tr>
                        <td class="pad">
                        <div class="alignment" style="text-align:center;">
                        <table border="0" cellpadding="0" cellspacing="0" class="social-table" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;" width="188px">
                        <tr>
                        <td style="padding:0 25px 0 5px;"><a href="https://www.facebook.com/breakersstoreeg/" target="_blank"><img alt="Facebook" height="32" src="{{site}}{% static 'img/facebook2x.png'%}" style="display: block; height: auto; border: 0;" title="Facebook" width="32"/></a></td>
                        <td style="padding:0 25px 0 5px;"><a href="https://twitter.com/" target="_blank"><img alt="Twitter" height="32" src="{{site}}{% static 'img/twitter2x.png'%}" style="display: block; height: auto; border: 0;" title="Twitter" width="32"/></a></td>
                        <td style="padding:0 25px 0 5px;"><a href="https://instagram.com/" target="_blank"><img alt="Instagram" height="32" src="{{site}}{% static 'img/instagram2x.png'%}" style="display: block; height: auto; border: 0;" title="Instagram" width="32"/></a></td>
                        </tr>
                        </table>
                        </div>
                        </td>
                        </tr>
                        </table>
                </div>
                
            </aside>
            
            {% block content %} {% endblock content %}
        </div>
    </div>

    <div class="page-modals">
        <div class="uk-flex-top" id="modal-report" data-uk-modal>
            <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical"><button class="uk-modal-close-default" type="button" data-uk-close></button>
                <h2 class="uk-modal-title">Report</h2>
                <form class="uk-form-stacked" action="#">
                    <div class="uk-margin">
                        <div class="uk-form-label">Subject</div>
                        <div class="uk-form-controls"><select class="js-select">
                                <option value="">Choose Subject</option>
                                <option value="Subject 1">Subject 1</option>
                                <option value="Subject 2">Subject 2</option>
                                <option value="Subject 3">Subject 3</option>
                            </select></div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label">Details</div>
                        <div class="uk-form-controls"><textarea class="uk-textarea" name="details" placeholder="Try to include all details..."></textarea></div>
                        <div class="uk-form-controls uk-margin-small-top">
                            <div data-uk-form-custom><input type="file"><button class="uk-button uk-button-default" type="button" tabindex="-1"><i class="ico_attach-circle"></i><span>Attach File</span></button></div>
                        </div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-grid uk-flex-right" data-uk-grid>
                            <div><button class="uk-button uk-button-small uk-button-link">Cancel</button></div>
                            <div><button class="uk-button uk-button-small uk-button-danger">Submit</button></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="uk-flex-top" id="modal-help" data-uk-modal>
            <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical"><button class="uk-modal-close-default" type="button" data-uk-close></button>
                <h2 class="uk-modal-title">Help</h2>
                <div class="uk-margin-small-left uk-margin-small-bottom uk-margin-medium-top">
                    <h4>Popular Q&A</h4>
                    <ul>
                        <li><img src="   {% static "img/svgico/clipboard-text.svg" %}" alt="icon"><span>How to Upload Your Developed Game</span></li>
                        <li><img src="   {% static "img/svgico/clipboard-text.svg" %}" alt="icon"><span>How to Go Live Stream</span></li>
                        <li><img src="   {% static "img/svgico/clipboard-text.svg" %}" alt="icon"><span>Get in touch with the Creator Support Team</span></li>
                    </ul>
                    <ul>
                        <li><a href="#!">browse all articles</a></li>
                        <li><a href="#!">Send Feedback</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

   
    <script src=" {% static "js/libs.js" %}"></script>
    <script src=" {% static "js/main.js" %}"></script>
</body>

</html>